"""Relational-DB Signature rows for stub 1.19 (mysql/mariadb/
postgresql/sqlite/mssql/oracle).

Spec: docs/superpowers/specs/2026-05-18-VULN-SCANNING-COOK-BOOK/01-information-gathering/19-sql-orm-errors.md
"""
from __future__ import annotations

from .signatures import Signature


RELATIONAL_SIGNATURES: tuple[Signature, ...] = (
    # --- mysql / mariadb ---
    Signature(
        id="mysql.syntax_error",
        family="mysql",
        name="MySQL syntax-error preamble",
        pattern=r"You have an error in your SQL syntax",
        pattern_type="literal",
        case_sensitive=False,
        confidence_hint="high",
        requires_context=False,
        description="Canonical MySQL parser-error preamble. Strong on its own.",
    ),
    Signature(
        id="mysql.mysqli_exception",
        family="mysql",
        name="PHP mysqli exception class",
        pattern=r"mysqli_sql_exception",
        pattern_type="literal",
        case_sensitive=True,
        confidence_hint="high",
        requires_context=False,
        description="PHP mysqli ext exception class name.",
    ),
    Signature(
        id="mysql.warning_prefix",
        family="mysql",
        name="PHP mysql_* warning prefix",
        pattern=r"Warning: mysql_",
        pattern_type="literal",
        case_sensitive=False,
        confidence_hint="high",
        requires_context=False,
        description="Legacy PHP mysql_* function warning prefix.",
    ),
    Signature(
        id="mysql.dotnet_exception",
        family="mysql",
        name=".NET MySql.Data exception",
        pattern=r"MySqlException",
        pattern_type="literal",
        case_sensitive=True,
        confidence_hint="medium",
        requires_context=True,
        description=".NET MySql.Data.MySqlClient.MySqlException class name.",
    ),
    Signature(
        id="mariadb.banner",
        family="mariadb",
        name="MariaDB banner",
        pattern=r"\bMariaDB\b",
        pattern_type="regex",
        case_sensitive=True,
        confidence_hint="medium",
        requires_context=True,
        description="MariaDB server identification.",
    ),

    # --- postgresql ---
    Signature(
        id="postgresql.syntax_error",
        family="postgresql",
        name="PostgreSQL syntax-error preamble",
        pattern=r"syntax error at or near",
        pattern_type="literal",
        case_sensitive=False,
        confidence_hint="high",
        requires_context=False,
        description="Canonical PostgreSQL parser error.",
    ),
    Signature(
        id="postgresql.pg_query",
        family="postgresql",
        name="PHP pg_query warning",
        pattern=r"pg_query",
        pattern_type="literal",
        case_sensitive=False,
        confidence_hint="medium",
        requires_context=True,
        description="PHP pg_query() function name in error context.",
    ),
    Signature(
        id="postgresql.psycopg",
        family="postgresql",
        name="psycopg driver",
        pattern=r"psycopg2?\.",
        pattern_type="regex",
        case_sensitive=True,
        confidence_hint="high",
        requires_context=False,
        description="Python psycopg driver module path in stack/error.",
    ),
    Signature(
        id="postgresql.npgsql",
        family="postgresql",
        name=".NET Npgsql exception",
        pattern=r"\bNpgsql\b",
        pattern_type="regex",
        case_sensitive=True,
        confidence_hint="high",
        requires_context=False,
        description=".NET Npgsql driver exception class.",
    ),

    # --- sqlite ---
    Signature(
        id="sqlite.operational_error",
        family="sqlite",
        name="Python sqlite3.OperationalError",
        pattern=r"sqlite3\.OperationalError",
        pattern_type="regex",
        case_sensitive=True,
        confidence_hint="high",
        requires_context=False,
        description="Python stdlib sqlite3 driver operational error.",
    ),
    Signature(
        id="sqlite.exception",
        family="sqlite",
        name="SQLiteException class",
        pattern=r"SQLiteException",
        pattern_type="literal",
        case_sensitive=True,
        confidence_hint="high",
        requires_context=False,
        description="Generic SQLiteException class name.",
    ),

    # --- mssql ---
    Signature(
        id="mssql.sqlclient_exception",
        family="mssql",
        name=".NET SqlClient.SqlException",
        pattern=r"System\.Data\.SqlClient\.SqlException",
        pattern_type="regex",
        case_sensitive=True,
        confidence_hint="high",
        requires_context=False,
        description=".NET System.Data.SqlClient.SqlException class.",
    ),
    Signature(
        id="mssql.ole_db_provider",
        family="mssql",
        name="OLE DB Provider for SQL Server",
        pattern=r"Microsoft OLE DB Provider for SQL Server",
        pattern_type="literal",
        case_sensitive=False,
        confidence_hint="high",
        requires_context=False,
        description="Classic ASP / OLE DB error banner.",
    ),
    Signature(
        id="mssql.native_client",
        family="mssql",
        name="SQL Server Native Client banner",
        pattern=r"SQL Server Native Client",
        pattern_type="literal",
        case_sensitive=False,
        confidence_hint="high",
        requires_context=False,
        description="SQL Server Native Client driver banner.",
    ),

    # --- oracle ---
    Signature(
        id="oracle.ora_code",
        family="oracle",
        name="Oracle ORA-#### code",
        pattern=r"\bORA-\d{4,5}\b",
        pattern_type="regex",
        case_sensitive=True,
        confidence_hint="high",
        requires_context=False,
        description="Oracle ORA-NNNNN error-code disclosure.",
    ),
    Signature(
        id="oracle.banner",
        family="oracle",
        name="Oracle error banner",
        pattern=r"\bOracle error\b",
        pattern_type="regex",
        case_sensitive=False,
        confidence_hint="medium",
        requires_context=True,
        description="Generic Oracle error banner.",
    ),
)
