# Generated by Django 5.1.15 on 2026-05-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanEvent',
        ),
    ]
