# Generated by Django 5.1.15 on 2026-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_delete_scanevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrun',
            name='stub_slug',
            field=models.CharField(help_text="Cookbook stub identifier (phase.spec form, e.g. '1.1').", max_length=64),
        ),
    ]
