"""HTTP fetch and CLI runner for the model scout.

Entry point for `bin/scout-models`. Hits the OpenRouter /models
endpoint, delegates scoring to `model_scout.py`, prints a table of
recommended env-var assignments, and writes `.env.model-scout`.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import httpx

from earn_money.agent.model_scout import (
    ModelInfo,
    parse_models_response,
    recommend_profiles,
    score_model,
)
from earn_money.agent.providers_openai_compat import OPENROUTER_BASE_URL
from earn_money.agent.task_router import TaskType

_ENV_FILE = ".env.model-scout"


def fetch_models_json(
    api_key: str,
    base_url: str = OPENROUTER_BASE_URL,
) -> dict:  # type: ignore[type-arg]
    """Fetch raw /models JSON from OpenRouter."""
    with httpx.Client(
        headers={"Authorization": f"Bearer {api_key}"},
        timeout=30.0,
    ) as client:
        resp = client.get(f"{base_url}/models")
        resp.raise_for_status()
        return resp.json()  # type: ignore[no-any-return]


def run_scout(*, root: Path | None = None, write_env: bool = True) -> None:
    """Discover free models, print recommendations, write .env.model-scout."""
    api_key = os.environ.get("OPENROUTER_API_KEY", "")
    base_url = os.environ.get("OPENROUTER_BASE_URL") or OPENROUTER_BASE_URL

    if not api_key:
        print("scout-models: OPENROUTER_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    print("Fetching model list from OpenRouter…")
    try:
        raw = fetch_models_json(api_key, base_url)
    except httpx.HTTPError as exc:
        print(f"scout-models: HTTP error — {exc}", file=sys.stderr)
        sys.exit(1)

    models = parse_models_response(raw)

    if not models:
        print("No free-tier models found — nothing to recommend.")
        return

    print(f"Found {len(models)} free-tier models.\n")
    _print_top_per_profile(models)

    recommendations = recommend_profiles(models)
    print("\nRecommended env-var assignments:")
    for var, mid in sorted(recommendations.items()):
        print(f"  {var}={mid}")

    if write_env:
        dest = (root or Path(".")) / _ENV_FILE
        _write_env_file(dest, recommendations)
        print(f"\nWritten to {dest}")
        print("Activate with: source .env.model-scout  (or set -a; . .env.model-scout)")


def _print_top_per_profile(models: list[ModelInfo]) -> None:
    print(f"{'Profile':<26}  {'Score':>5}  Model")
    print("-" * 72)
    for task in TaskType:
        ranked = sorted(models, key=lambda m: score_model(m, task), reverse=True)
        best = ranked[0]
        print(f"{task.value:<26}  {score_model(best, task):>5}  {best.id}")


def _write_env_file(path: Path, assignments: dict[str, str]) -> None:
    lines = ["# Auto-generated by bin/scout-models — source to activate\n"]
    for var, mid in sorted(assignments.items()):
        lines.append(f"{var}={mid}\n")
    path.write_text("".join(lines))


if __name__ == "__main__":
    run_scout()
