# Generated by Django 5.1.15 on 2026-05-23 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0003_alter_scanrun_stub_slug'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(max_length=32)),
                ('args_redacted', models.JSONField(default=dict)),
                ('goal', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('hypothesis', models.TextField(blank=True, default='')),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid_schema', 'Invalid schema'), ('denied_phase', 'Denied by phase'), ('denied_roe', 'Denied by RoE'), ('denied_budget', 'Denied by budget'), ('denied_scope', 'Denied by scope')], max_length=20)),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('skipped', 'Skipped'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('denial_reason', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation_type', models.CharField(choices=[('page', 'Page'), ('http', 'HTTP'), ('stub', 'Stub'), ('tool', 'Tool'), ('asset', 'Asset')], max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('artifact_refs', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('redactions', models.JSONField(blank=True, default=list)),
                ('is_delta', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='agent.agentaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autonomy_mode', models.CharField(choices=[('lab_free_run', 'Lab free run'), ('real_checkpointed', 'Real checkpointed')], max_length=20)),
                ('current_phase', models.CharField(choices=[('recon', 'Recon'), ('enumerate', 'Enumerate'), ('probe', 'Probe'), ('verify', 'Verify'), ('report', 'Report')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=16)),
                ('mission_profile', models.CharField(max_length=64)),
                ('model_policy', models.JSONField(default=dict)),
                ('roe_snapshot', models.JSONField(default=dict)),
                ('mission_budget', models.JSONField(default=dict)),
                ('consumed_budget', models.JSONField(default=dict)),
                ('progress_counters', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='scans.scanrun')),
                ('scan_target_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_session', to='scans.scantargetrun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='targets.scantarget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField()),
                ('phase', models.CharField(choices=[('recon', 'Recon'), ('enumerate', 'Enumerate'), ('probe', 'Probe'), ('verify', 'Verify'), ('report', 'Report')], max_length=16)),
                ('model', models.CharField(max_length=128)),
                ('prompt_artifact_ref', models.CharField(blank=True, default='', max_length=256)),
                ('response_artifact_ref', models.CharField(blank=True, default='', max_length=256)),
                ('prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('response_hash', models.CharField(blank=True, default='', max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('action_proposed', 'Action proposed'), ('action_denied', 'Action denied'), ('action_executed', 'Action executed'), ('completed', 'Completed'), ('error', 'Error')], default='started', max_length=20)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='agent.agentsession')),
            ],
            options={
                'ordering': ('session', 'index'),
            },
        ),
        migrations.CreateModel(
            name='AgentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('hypothesis', 'Hypothesis'), ('gap', 'Gap'), ('credential_label', 'Credential label'), ('route', 'Route'), ('parameter', 'Parameter'), ('candidate', 'Candidate')], max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='agent.agentsession')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='agent.agentturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agentaction',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='agent.agentturn'),
        ),
        migrations.AddConstraint(
            model_name='agentturn',
            constraint=models.UniqueConstraint(fields=('session', 'index'), name='uniq_turn_index_per_session'),
        ),
    ]
