# Generated by Django 5.1.15 on 2026-05-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnote',
            name='note_type',
            field=models.CharField(choices=[('hypothesis', 'Hypothesis'), ('gap', 'Gap'), ('credential_label', 'Credential label'), ('route', 'Route'), ('parameter', 'Parameter'), ('candidate', 'Candidate'), ('form', 'Form')], max_length=20),
        ),
    ]
