# Generated by Django 5.1.15 on 2026-05-18 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0002_delete_scanevent'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('system.test', 'System test event')], max_length=64)),
                ('subject_type', models.CharField(blank=True, default='', max_length=32)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=8)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scans.scanrun')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='targets.scantarget')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['scan_run', 'created_at'], name='events_even_scan_ru_14364e_idx'), models.Index(fields=['type', 'created_at'], name='events_even_type_e33440_idx'), models.Index(fields=['subject_type', 'subject_id'], name='events_even_subject_20f7cd_idx')],
            },
        ),
    ]
