# Generated by Django 5.1.15 on 2026-05-18 21:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('system.test', 'System test event'), ('project.created', 'Project created'), ('project.updated', 'Project updated'), ('project.deleted', 'Project deleted'), ('target.created', 'Target created'), ('target.updated', 'Target updated'), ('target.deleted', 'Target deleted'), ('scan_run.created', 'Scan run created'), ('scan_run.started', 'Scan run started'), ('scan_run.paused', 'Scan run paused'), ('scan_run.resumed', 'Scan run resumed'), ('scan_run.stopped', 'Scan run stopped')], max_length=64),
        ),
    ]
