# Generated by Django 5.1.15 on 2026-05-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_data_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('system.test', 'System test event'), ('project.created', 'Project created'), ('project.updated', 'Project updated'), ('project.deleted', 'Project deleted'), ('target.created', 'Target created'), ('target.updated', 'Target updated'), ('target.deleted', 'Target deleted'), ('scan_run.created', 'Scan run created'), ('scan_run.started', 'Scan run started'), ('scan_run.paused', 'Scan run paused'), ('scan_run.resumed', 'Scan run resumed'), ('scan_run.stopped', 'Scan run stopped'), ('scan_run.stopped_final', 'Scan run finalised after stop'), ('scan_run.done', 'Scan run completed'), ('scan_target_run.started', 'Scan target run started'), ('scan_target_run.done', 'Scan target run completed'), ('scan_target_run.stopped', 'Scan target run stopped')], max_length=64),
        ),
    ]
