# Generated by Django 5.1.15 on 2026-05-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('system.test', 'System test event'), ('project.created', 'Project created'), ('project.updated', 'Project updated'), ('project.deleted', 'Project deleted'), ('target.created', 'Target created'), ('target.updated', 'Target updated'), ('target.deleted', 'Target deleted'), ('scan_run.created', 'Scan run created'), ('scan_run.started', 'Scan run started'), ('scan_run.paused', 'Scan run paused'), ('scan_run.resumed', 'Scan run resumed'), ('scan_run.stopped', 'Scan run stopped'), ('scan_run.stopped_final', 'Scan run finalised after stop'), ('scan_run.done', 'Scan run completed'), ('scan_run.failed', 'Scan run failed'), ('scan_target_run.started', 'Scan target run started'), ('scan_target_run.done', 'Scan target run completed'), ('scan_target_run.stopped', 'Scan target run stopped'), ('scan_target_run.failed', 'Scan target run failed'), ('finding.created', 'Finding created'), ('finding.status_changed', 'Finding status changed'), ('scan.out_of_scope_rejected', 'Out-of-scope candidate URL rejected'), ('scan.edge_blocking_detected', 'Edge / WAF blocked probes before origin'), ('auth.probe_refused', 'Active auth probe refused by RoE / safety gate'), ('auth.finding_candidate', 'Auth Finding emitted with status=candidate'), ('auth.fixture_required', 'Stub refused live target — fixture validation missing'), ('agent.session_started', 'Agent session started'), ('agent.action_executed', 'Agent action executed'), ('agent.action_denied', 'Agent action denied'), ('agent.phase_changed', 'Agent phase changed'), ('agent.note_created', 'Agent note created'), ('agent.mission_finished', 'Agent mission finished')], max_length=64),
        ),
    ]
