# Generated by Django 5.1.15 on 2026-05-18 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findings', '0001_initial'),
        ('scans', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('header', 'Header'), ('cookie', 'Cookie'), ('html', 'HTML'), ('script', 'Script'), ('css', 'CSS'), ('favicon', 'Favicon'), ('path', 'Path'), ('meta', 'Meta'), ('dns', 'DNS')], max_length=16)),
                ('url', models.URLField(max_length=2048)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('field', models.CharField(blank=True, default='', max_length=128)),
                ('matched_value', models.TextField(blank=True, default='')),
                ('raw_excerpt', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, default='', max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='findings.finding')),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='scans.scanrun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='targets.scantarget')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['scan_run', 'created_at'], name='evidence_ev_scan_ru_adc70f_idx'), models.Index(fields=['target', 'source'], name='evidence_ev_target__891e88_idx')],
            },
        ),
    ]
