# Generated by Django 5.1.15 on 2026-05-18 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stub_slug', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('severity', models.CharField(blank=True, default='', max_length=16)),
                ('confidence', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('stale', 'Stale')], default='candidate', max_length=16)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scanrun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='targets.scantarget')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['scan_run', 'status'], name='findings_fi_scan_ru_c40015_idx'), models.Index(fields=['stub_slug'], name='findings_fi_stub_sl_64e96f_idx')],
            },
        ),
    ]
