"""Tests for stub 1.9 seeded candidate data."""
from __future__ import annotations

import unittest

from ..candidates import DEPRECATION_HEADERS, SEEDED_PATHS, STALE_TOKENS


class SeededPathsTests(unittest.TestCase):
    def test_all_paths_start_with_slash(self) -> None:
        for path in SEEDED_PATHS:
            assert path.startswith("/"), path

    def test_slash_and_no_slash_variants_present(self) -> None:
        # Spec §Default stale path dictionary lists slash AND no-slash
        # variants for each base — `/v1` AND `/v1/`, etc. Keeping both
        # lets the runner observe the server's preference; dedup happens
        # at the finding stage by comparing response equivalence.
        for base in ("/old", "/legacy", "/deprecated", "/v0", "/v1"):
            assert base in SEEDED_PATHS, base
            assert f"{base}/" in SEEDED_PATHS, base

    def test_api_legacy_paths_present(self) -> None:
        for path in ("/api/old", "/api/legacy", "/api/deprecated"):
            assert path in SEEDED_PATHS, path

    def test_version_paths_v0_v1_only(self) -> None:
        # MVP: v0 and v1 are the canonical legacy versions. Higher
        # versions (v2+) are NOT seeded — they'd be generated by the
        # version-shadow expander from observed paths, which is
        # deferred.
        for path in ("/api/v0", "/api/v1", "/v0", "/v1", "/rest/v0", "/rest/v1"):
            assert path in SEEDED_PATHS
        for path in ("/api/v2", "/v2", "/api/v3"):
            assert path not in SEEDED_PATHS

    def test_no_duplicate_paths(self) -> None:
        assert len(SEEDED_PATHS) == len(set(SEEDED_PATHS))


class StaleTokensTests(unittest.TestCase):
    def test_core_tokens_present(self) -> None:
        for token in ("old", "legacy", "deprecated", "sunset", "v0", "v1"):
            assert token in STALE_TOKENS

    def test_lowercase_only(self) -> None:
        # Path-segment comparison is done after .lower() — tokens stored
        # in lowercase save a per-token .lower() on every comparison.
        for token in STALE_TOKENS:
            assert token == token.lower(), token

    def test_no_duplicates(self) -> None:
        assert len(STALE_TOKENS) == len(set(STALE_TOKENS))


class DeprecationHeadersTests(unittest.TestCase):
    def test_rfc_standard_headers_present(self) -> None:
        # Deprecation (RFC 8594) + Sunset (RFC 8594) are the canonical
        # IETF headers. Warning (RFC 7234) carries the 299-code variant
        # the spec calls out. Link with rel="deprecation|sunset" hides
        # behind a generic Link header — extraction happens later.
        for header in ("Deprecation", "Sunset", "Warning", "Link"):
            assert header in DEPRECATION_HEADERS

    def test_preserves_header_case(self) -> None:
        # HTTP headers are case-insensitive on the wire but the spec
        # writes the canonical mixed-case form — preserving it makes
        # Evidence diffs readable. Comparison code uses .lower().
        assert "Deprecation" in DEPRECATION_HEADERS
        assert "deprecation" not in DEPRECATION_HEADERS
