"""Signature library for stub 1.2 server-headers.

Spec: docs/superpowers/specs/2026-05-18-VULN-SCANNING-COOK-BOOK/01-information-gathering/02-server-headers.md
"""
from __future__ import annotations

from typing import Any


TECHNOLOGY_CATEGORIES: set[str] = {
    "web_server",
    "app_runtime",
    "framework",
    "proxy",
    "cdn",
    "cache",
    "load_balancer",
    "security_middleware",
    "unknown",
}


SIGNATURES: list[dict[str, Any]] = [
    {
        "id": "server_nginx",
        "header_name": "server",
        "value_pattern": "nginx",
        "match_type": "contains",
        "technology": "nginx",
        "technology_category": "web_server",
        "version_regex": r"nginx/([0-9.]+)",
        "confidence": "high",
    },
    {
        "id": "server_apache",
        "header_name": "server",
        "value_pattern": "Apache",
        "match_type": "contains",
        "technology": "apache_httpd",
        "technology_category": "web_server",
        "version_regex": r"Apache/([0-9.]+)",
        "confidence": "high",
    },
    {
        "id": "server_iis",
        "header_name": "server",
        "value_pattern": "Microsoft-IIS",
        "match_type": "contains",
        "technology": "iis",
        "technology_category": "web_server",
        "version_regex": r"Microsoft-IIS/([0-9.]+)",
        "confidence": "high",
    },
    {
        "id": "server_caddy",
        "header_name": "server",
        "value_pattern": "Caddy",
        "match_type": "contains",
        "technology": "caddy",
        "technology_category": "web_server",
        "version_regex": None,
        "confidence": "high",
    },
    {
        "id": "powered_by_express",
        "header_name": "x-powered-by",
        "value_pattern": "Express",
        "match_type": "contains",
        "technology": "express",
        "technology_category": "framework",
        "version_regex": None,
        "confidence": "high",
    },
    {
        "id": "powered_by_php",
        "header_name": "x-powered-by",
        "value_pattern": "PHP",
        "match_type": "contains",
        "technology": "php",
        "technology_category": "app_runtime",
        "version_regex": r"PHP/([0-9.]+)",
        "confidence": "high",
    },
    {
        "id": "aspnet_version",
        "header_name": "x-aspnet-version",
        "value_pattern": ".+",
        "match_type": "regex",
        "technology": "aspnet",
        "technology_category": "framework",
        "version_regex": r"^([0-9.]+)$",
        "confidence": "high",
    },
    {
        "id": "cloudflare_cf_ray",
        "header_name": "cf-ray",
        "value_pattern": ".+",
        "match_type": "regex",
        "technology": "cloudflare",
        "technology_category": "cdn",
        "version_regex": None,
        "confidence": "high",
    },
    {
        "id": "cloudflare_cache_status",
        "header_name": "cf-cache-status",
        "value_pattern": ".+",
        "match_type": "regex",
        "technology": "cloudflare",
        "technology_category": "cdn",
        "version_regex": None,
        "confidence": "high",
    },
    {
        "id": "cloudfront_amz_cf_id",
        "header_name": "x-amz-cf-id",
        "value_pattern": ".+",
        "match_type": "regex",
        "technology": "aws_cloudfront",
        "technology_category": "cdn",
        "version_regex": None,
        "confidence": "high",
    },
    {
        "id": "varnish_header",
        "header_name": "x-varnish",
        "value_pattern": ".+",
        "match_type": "regex",
        "technology": "varnish",
        "technology_category": "cache",
        "version_regex": None,
        "confidence": "high",
    },
    {
        "id": "varnish_via",
        "header_name": "via",
        "value_pattern": "varnish",
        "match_type": "contains",
        "technology": "varnish",
        "technology_category": "cache",
        "version_regex": None,
        "confidence": "medium",
    },
    {
        "id": "envoy_upstream_time",
        "header_name": "x-envoy-upstream-service-time",
        "value_pattern": ".+",
        "match_type": "regex",
        "technology": "envoy",
        "technology_category": "proxy",
        "version_regex": None,
        "confidence": "high",
    },
    {
        "id": "kong_upstream_latency",
        "header_name": "x-kong-upstream-latency",
        "value_pattern": ".+",
        "match_type": "regex",
        "technology": "kong",
        "technology_category": "proxy",
        "version_regex": None,
        "confidence": "high",
    },
]
