"""Regenerate PROGRESS.md for the vuln-scanning cookbook.

Walks docs/superpowers/specs/2026-05-18-VULN-SCANNING-COOK-BOOK/, reads each
per-bullet spec's `**Status:**` and `**Fixture:**` lines, and writes a grouped
checklist at the cookbook root. Idempotent — re-run any time. Never hand-edit
PROGRESS.md; update the per-spec stubs and regenerate.

Status values recognised: pending (default), in-progress, blocked, done.
Anything else renders as [?] in the output.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

COOKBOOK = (
    Path(__file__).resolve().parent.parent
    / "docs/superpowers/specs/2026-05-18-VULN-SCANNING-COOK-BOOK"
)
OUT = COOKBOOK / "PROGRESS.md"

PHASE_DIR_RE = re.compile(r"^(\d{2})-(.+)$")
SPEC_FILE_RE = re.compile(r"^(\d{2})-(.+)\.md$")
STATUS_RE = re.compile(r"^\*\*Status:\*\*\s+([a-z-]+)", re.MULTILINE)
FIXTURE_RE = re.compile(r"^\*\*Fixture:\*\*\s+([^\n]+)", re.MULTILINE)
SPEC_TITLE_RE = re.compile(r"^# \d+\.\d+\s+(.+)$", re.MULTILINE)
OVERVIEW_TITLE_RE = re.compile(r"^# \d+\.\s*(.+)$", re.MULTILINE)

STATUS_BOX = {
    "pending": "[ ]",
    "in-progress": "[~]",
    "blocked": "[!]",
    "done": "[x]",
}


def parse_spec(path: Path) -> tuple[str, str, str]:
    """Return (title, status, fixture) for a single spec file."""
    text = path.read_text()
    title_m = SPEC_TITLE_RE.search(text)
    title = title_m.group(1).strip() if title_m else path.stem
    status_m = STATUS_RE.search(text)
    status = status_m.group(1) if status_m else "pending"
    fixture_m = FIXTURE_RE.search(text)
    fixture = fixture_m.group(1).strip() if fixture_m else "tbd"
    return title, status, fixture


def phase_title(phase_dir: Path, fallback: str) -> str:
    overview = phase_dir / "00-overview.md"
    if overview.exists():
        m = OVERVIEW_TITLE_RE.search(overview.read_text())
        if m:
            return m.group(1).strip()
    return fallback.replace("-", " ")


def main() -> int:
    if not COOKBOOK.exists():
        print(f"error: cookbook folder not found: {COOKBOOK}", file=sys.stderr)
        return 1

    phases: list[tuple[int, str, str, list[tuple[str, str, str, str, str]], int]] = []
    total_done = 0
    total_specs = 0
    phases_shipped = 0

    for phase_dir in sorted(COOKBOOK.iterdir()):
        if not phase_dir.is_dir():
            continue
        dir_match = PHASE_DIR_RE.match(phase_dir.name)
        if not dir_match:
            continue
        phase_n_str, phase_slug = dir_match.group(1), dir_match.group(2)
        title = phase_title(phase_dir, phase_slug)

        specs: list[tuple[str, str, str, str, str]] = []
        for spec_path in sorted(phase_dir.glob("[0-9][0-9]-*.md")):
            if spec_path.name == "00-overview.md":
                continue
            spec_match = SPEC_FILE_RE.match(spec_path.name)
            if not spec_match:
                continue
            spec_n, spec_slug = spec_match.group(1), spec_match.group(2)
            spec_title, status, fixture = parse_spec(spec_path)
            specs.append((spec_n, spec_slug, spec_title, status, fixture))

        done = sum(1 for entry in specs if entry[3] == "done")
        total_done += done
        total_specs += len(specs)
        if specs and done == len(specs):
            phases_shipped += 1

        phases.append((int(phase_n_str), phase_slug, title, specs, done))

    out_lines: list[str] = [
        "# Cookbook Progress",
        "",
        "Auto-generated by `scripts/cookbook_progress.py`. Do not hand-edit —",
        "update the per-spec `**Status:**` and `**Fixture:**` lines instead,",
        "then re-run the script.",
        "",
        f"**Overall:** {total_done}/{total_specs} specs done · "
        f"{phases_shipped}/{len(phases)} phases shipped.",
        "",
    ]

    for phase_n, phase_slug, title, specs, done in phases:
        out_lines.append(f"## Phase {phase_n} — {title} ({done}/{len(specs)})")
        out_lines.append("")
        for spec_n, spec_slug, spec_title, status, fixture in specs:
            box = STATUS_BOX.get(status, "[?]")
            link = f"{phase_n:02d}-{phase_slug}/{spec_n}-{spec_slug}.md"
            fix = f" — fixture: `{fixture}`" if fixture != "tbd" else ""
            out_lines.append(
                f"- {box} [`{spec_n}-{spec_slug}`]({link}) — {spec_title}{fix}"
            )
        out_lines.append("")

    OUT.write_text("\n".join(out_lines))
    print(
        f"wrote PROGRESS.md: {total_specs} specs, {total_done} done, "
        f"{phases_shipped}/{len(phases)} phases shipped"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
